### ISSUE TITLE
[Suggestion] Add Laravel integration

### ISSUE THREAD

**Issue by MarkRedeman** [qandidate-labs/broadway#104]
I will start working on a broadway integration for Laravel this week / month.
Should I create a separate repository or, make a pull request once it's finished?

**Comment by asm89** [comment]
@MarkRedeman still working on this? I'd love to have this.

**Comment by MarkRedeman** [comment]
It's on my todo list, but I have two deadlines this month that take priority. I will probably start working on this again in February.

**Comment by nWidart** [comment]
I'd be interested too. I'm playing with it in a [test repo](https://github.com/nWidart/Laravel-Broadway) , haven't had the need for something special for laravel.
What do you have in mind for the "Laravel integration" ?

Cheers, :smiley:

**Comment by harikt** [comment]
I believe a separate repo is nice. Please integration for frameworks can be standalone.  Not to be tight to a library.

**Comment by nWidart** [comment]
I was thinking the same thing, I also think it would be best to have it separate to keep this package clean.

I've started working on a Laravel Service Provider. I managed to get everything working, for the write side. Only, with a `InMemoryEventStore`. I would like to use the `Broadway\EventStore\DBALEventStore` but don't know how to get its dependencies. I'm using the [Laravel-Doctrine](https://github.com/mitchellvanw/laravel-doctrine) package. 
I've summarized the issue(s) [on a gist](https://gist.github.com/nWidart/8446ecc5daf05d12426f#event-store). Would appreciate if someone could point me in the right direction.

**Comment by MarkRedeman** [comment]
@nWidart yes, basically I wanted to add some bindings like the `LaravelBroadwayServiceProvider` from your example app is doing and add the necessary migrations.
Since Laravel 5 has some nice command bus features, I wanted to wait for its release such that we can build upon those features.

**Comment by nWidart** [comment]
Ah yes I understand. In theory it should be a matter of binding `Broadway\CommandHandling\CommandBusInterface` to a Laravel command bus, if it's compatible. Same for the events, since l5 will have that too.

**Comment by MarkRedeman** [comment]
Exactly. We could also make it compatible with L4, but I'm not sure if that will be necessary.

**Comment by nWidart** [comment]
Got the write part completely working with the `DBALEventStore`. :smiley: 

Now the read model... for which they aren't any documentation / examples.

**Comment by mbadolato** [comment]
@nWidart Does the [demo app](https://github.com/qandidate-labs/broadway-demo) give you the read model example you need, or are you looking for something further?

**Comment by nWidart** [comment]
I’m indeed looking at the demo app, but don’t find it very clear, yet. Probably just because I’m still getting used to ES/CQRS. A read model example with the parts/part manufacturer would have been nice, to stay in the same context.

I’m still confused on how the read model works. I understand it uses elastic search as a read model, but what’s the link with the event_store (mysql for instance) ? 
Or does the read model somehow indexes something to ES, and reads it ? But that would defeat the purpose of separating the write/read. 

On the `PeopleThatBoughtThisProductAlsoBoughtController` controller, I see that a `find` method is called on the repository, but can’t seem to find that `find` method on the `EventSourcingRepository`.
Also that controller doesn’t call the 2 classes inside the `ReadModel` namespace. Are they just there for demonstration of testing maybe ?

It’s late here so maybe I’m just missing something obvious. :)
I will actually try to implement a read model tomorrow based on the demo app. 

Thank you,

**Comment by wjzijderveld** [comment]
A read model is created as a response on an event that happened.
In the demo application, you can find an example in the [PeopleThatBoughtThisProductAlsoBoughtProjector](https://github.com/qandidate-labs/broadway-demo/blob/master/src/BroadwayDemo/ReadModel/PeopleThatBoughtThisProductAlsoBoughtProjector.php).

A read model projector listens to events, the same events that are processed by the aggregate root. A projector uses a repository to create the read model, but this is not the `EventSourcingRepository`. It is a special [read model repository](https://github.com/qandidate-labs/broadway/blob/78838a5ffa53388bd49849c3e60c5ed0d1f92fa4/src/Broadway/ReadModel/RepositoryInterface.php), in the case of the demo application, it's the [ElasticsearchRepository](https://github.com/qandidate-labs/broadway/blob/78838a5ffa53388bd49849c3e60c5ed0d1f92fa4/src/Broadway/ReadModel/ElasticSearch/ElasticSearchRepository.php).

So the controller you were talking about actually does use both of the classes in the ReadModel namespace, they are just not type-hinted anywhere :smile: It queries the read model repository and returns the result as a JsonResponse.

Hope this clarifies it a bit..

**Comment by nWidart** [comment]
I see, very helpful, thank you! Will implement this today hopefully. :)

**Comment by MarkRedeman** [comment]
@nWidart in your case you'd want the `SimpleEventBus` to subscribe to `PartsThatWereManufacturedProjector` and have the repository that is used by your handler extend the `EventSourcingRepository`, such that each of the events that is added to the repository is also [published to your event bus](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/EventSourcing/EventSourcingRepository.php#L83).

See the [BasketRepository](https://github.com/qandidate-labs/broadway-demo/blob/master/src/BroadwayDemo/Basket/BasketRepository.php) on the broadway example repo for an example.

Subscribing to the eventbus can be done in any arbitrary place. In Laravel it is common to do this in an `events.php` file that is included in the `global.php` file, or in a service provider.

**Comment by nWidart** [comment]
Oh okay, the `EventStoreRepository` should be used in the projector class. This is done [here](https://github.com/nWidart/Laravel-Broadway/blob/master/Modules/Parts/PartServiceProvider.php#L21-L23) for now as a test. But the `applyPartWasManufactured` is still not called. Also tried a die&dump in the `handle` of the `Broadway\ReadModelProjector` class which is also not called.

About the location of the events, since laravel 5 uses Service Providers for pretty much everything, it might be a good idea to do it in a SP.

**Comment by nWidart** [comment]
A first packaged version is [available](https://github.com/nWidart/Laravel-broadway). 
There are still things to polish, like the read model settings and its service provider. Also adding some custom artisan commands to generate commands+handlers.

Feedback welcome :smiley:

**Comment by wjzijderveld** [comment]
Closing this as it's been out there for a while now :smile:

**Comment by nWidart** [comment]
:+1: :smile:
