### ISSUE TITLE
In the EventSourcedAggregateRoot the apply method is marked as internal

### ISSUE THREAD

**Issue by wjzijderveld** [qandidate-labs/broadway#173]
https://github.com/qandidate-labs/broadway/blob/26ab0d8e527c990169727a92d59faf24f0f256cd/src/Broadway/EventSourcing/EventSourcedAggregateRoot.php#L35

As you would use this from your aggregate, I don't see it as internal. Maybe we actually meant 'inheritDoc' there?

**Comment by tPl0ch** [comment]
@wjzijderveld Definately, since you call the method i.e. in static factory methods.

**Comment by mbadolato** [comment]
Yeah the method being crossed out in my IDE has always annoyed me. I've never seen it as internal either. Not to mention, the phpDoc site lists the description of internal as:

> Mark documentation as private, internal to the software project

which means the documentation is internal, not the method's usage.

The apply() method is not part of the AggregateRoot interface, however, so I don't know that inheritdoc was meant. Maybe it was marked as internal so that command handlers wouldn't be tempted to call the AR's apply method themselves? Regardless, removing it is probably a good idea.

**Comment by wjzijderveld** [comment]
Yeah, the inheritDoc was just a random thought of mine. Noticed it didn't make any sense when I addressed the issue
