### ISSUE TITLE
Event sourced aggregate with multiple (N) event sourced entities.

### ISSUE THREAD

**Issue by bweston92** [qandidate-labs/broadway#186]
I have an aggregate that has a collection of child entities but one is a collection of entities called `assets` how would I handle returning these in `getChildEntities` if I want them back in the `assets` private variable. For example

```
class Contact extends EventSourcedEntity {}
class Loan extends EventSourcedEntity {}
interface Asset {}
class Property extends EventSourcedEntity implements Asset {}

class Deal extends EventSourcedAggregateRoute
{
  private $contact;
  private $loan;
  private $assets = [];

  public function applyDealAssetPropertyCreated(DealAssetPropertyCreated $event)
  {
    $asset = Property; // Construct the asset.
    $asset->initialiseAsset($event);

    array_push($this->assets, $asset);
  }

  public function getChildEntities()
  {
    return [$this->contact, $this->loan, $this->assets];
  }
}
```

Sorry, I'm new to this pattern but appreciate any help.

**Comment by wjzijderveld** [comment]
Something like `return array_merge([$this->contact, $this->loan], $this->assets);`?

**Comment by codeliner** [comment]
Hi Bradley,

sorry for hijacking your thread! 

@wjzijderveld I don't think your suggestion is a good idea, because the [EventSourcedAggregateRoot::handleRecursively](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/EventSourcing/EventSourcedAggregateRoot.php#L91) would pass all assets events to all Asset entities without checking the id of the Asset. IMHO this would lead to an unexpected result because all Assets replay the events of all other Assets too.

@bweston92 Bradley, try to avoid collections of child entities. `Asset` can be a aggregate root too, you only need to reference the `Asset::id` in the `Deal` AR.

**Comment by bweston92** [comment]
@codeliner I went on their IRC, come to an understanding to get the DDD part right first then in a few months move to ES.

**Comment by codeliner** [comment]
@bweston92 :+1:

**Comment by wjzijderveld** [comment]
@codeliner Well, you need to do that anyway if you have multiple assets like @bweston92 has. And the child entities that don't listen to the event won't receive it either.
